# Generated by Django 2.0.3 on 2018-04-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='DailyExercisePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('friday', models.ManyToManyField(blank=True, related_name='friday', to='clients.DailyExercisePlan')),
                ('members', models.ManyToManyField(blank=True, through='clients.Membership', to='clients.Client')),
                ('monday', models.ManyToManyField(blank=True, related_name='monday', to='clients.DailyExercisePlan')),
                ('saturday', models.ManyToManyField(blank=True, related_name='saturday', to='clients.DailyExercisePlan')),
                ('sunday', models.ManyToManyField(blank=True, related_name='sunday', to='clients.DailyExercisePlan')),
                ('thursday', models.ManyToManyField(blank=True, related_name='thursday', to='clients.DailyExercisePlan')),
                ('tuesday', models.ManyToManyField(blank=True, related_name='tuesday', to='clients.DailyExercisePlan')),
                ('wednensday', models.ManyToManyField(blank=True, related_name='wednensday', to='clients.DailyExercisePlan')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='workoutplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.WorkoutPlan'),
        ),
        migrations.AddField(
            model_name='dailyexerciseplan',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='clients.Exercise'),
        ),
        migrations.AddField(
            model_name='client',
            name='workout_plans',
            field=models.ManyToManyField(blank=True, through='clients.Membership', to='clients.WorkoutPlan'),
        ),
    ]
